export const ErrorCode = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  DUPLICATE_REPORT: "DUPLICATE_REPORT",
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
  LAST_RECORD: "LAST_RECORD",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ErrorStatus: Record<ErrorCode, number> = {
  INVALID_CREDENTIALS: 401,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  DUPLICATE_REPORT: 409,
  DUPLICATE_EMAIL: 409,
  LAST_RECORD: 400,
  VALIDATION_ERROR: 422,
  INTERNAL_SERVER_ERROR: 500,
};
